CREATE TABLE "stores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "franchise_id" INTEGER,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "franchises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "password" TEXT NOT NULL,
  "token" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "store_admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "store_id" INTEGER,
  "franchise_id" INTEGER,
  "name" TEXT NOT NULL,
  "username" TEXT NOT NULL UNIQUE,
  "password_hash" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "card_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "franchise_id" INTEGER,
  "name" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" INTEGER NOT NULL,
  "card_type_id" INTEGER NOT NULL,
  "points" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "campaigns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" INTEGER NOT NULL,
  "points" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "campaign_redeems" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "campaign_id" INTEGER NOT NULL,
  "card_id" INTEGER NOT NULL,
  "amount" INTEGER NOT NULL,
  "points" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "purchase_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" INTEGER NOT NULL,
  "points" INTEGER NOT NULL,
  "description" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "purchases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "purchase_type_id" INTEGER NOT NULL,
  "card_id" INTEGER NOT NULL,
  "points" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "store_theme" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "store_id" INTEGER NOT NULL,
  "primary_color" TEXT NOT NULL,
  "secondary_color" TEXT NOT NULL,
  "background_color" TEXT NOT NULL,
  "text_color" TEXT NOT NULL,
  "stamp_image_url" TEXT NOT NULL,
  "slot_image_url" TEXT NOT NULL,
  "card_background_image_url" TEXT NOT NULL,
  "logo_url" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "franchise_theme" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "franchise_id" INTEGER NOT NULL UNIQUE,
  "primary_color" TEXT NOT NULL,
  "secondary_color" TEXT NOT NULL,
  "background_color" TEXT NOT NULL,
  "text_color" TEXT NOT NULL,
  "stamp_image_url" TEXT NOT NULL,
  "slot_image_url" TEXT NOT NULL,
  "card_background_image_url" TEXT NOT NULL,
  "logo_url" TEXT NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "push_notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" INTEGER NOT NULL,
  "status" INTEGER NOT NULL,
  "description" TEXT NOT NULL,
  "message" TEXT NOT NULL,
  "push_date" TIMESTAMPTZ NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "push_notification_cards" (
  "push_notification_id" INTEGER NOT NULL,
  "card_id" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  PRIMARY KEY ("push_notification_id", "card_id")
);

CREATE TABLE "campaign_stores" (
  "campaign_id" INTEGER NOT NULL,
  "store_id" INTEGER NOT NULL,
  "created_at" TIMESTAMPTZ NOT NULL,
  "updated_at" TIMESTAMPTZ NOT NULL,
  PRIMARY KEY ("campaign_id", "store_id")
);

CREATE TABLE "fidely_admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" TEXT NOT NULL,
  "username" TEXT NOT NULL,
  "password_hash" TEXT NOT NULL,
  "role" INTEGER NOT NULL
);

CREATE UNIQUE INDEX "uq_fidely_admin_username"
  ON "fidely_admin" ("username");

CREATE TABLE "admin_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "admin_type" TEXT NOT NULL,
  "admin_id" INTEGER NOT NULL,
  "session_token_hash" TEXT NOT NULL,
  "expires_at" TIMESTAMPTZ NOT NULL,
  "revoked_at" TIMESTAMPTZ,
  "created_at" TIMESTAMPTZ NOT NULL,
  "last_seen_at" TIMESTAMPTZ,
  CONSTRAINT "chk_admin_sessions_admin_type"
    CHECK ("admin_type" IN ('store_admin', 'fidely_admin'))
);

CREATE UNIQUE INDEX "uq_admin_sessions_session_token_hash"
  ON "admin_sessions" ("session_token_hash");

CREATE INDEX "idx_admin_sessions_admin_lookup"
  ON "admin_sessions" ("admin_type", "admin_id");

CREATE INDEX "idx_admin_sessions_expires_at"
  ON "admin_sessions" ("expires_at");

ALTER TABLE "store_admin"
  ADD CONSTRAINT "fk_store_admin_store_id"
  FOREIGN KEY ("store_id") REFERENCES "stores" ("id");

ALTER TABLE "store_admin"
  ADD CONSTRAINT "fk_store_admin_franchise_id"
  FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "stores"
  ADD CONSTRAINT "fk_stores_franchise_id"
  FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "card_types"
  ADD CONSTRAINT "fk_card_types_franchise_id"
  FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "cards"
  ADD CONSTRAINT "fk_cards_user_id"
  FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cards"
  ADD CONSTRAINT "fk_cards_card_type_id"
  FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "campaigns"
  ADD CONSTRAINT "fk_campaigns_card_type_id"
  FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "campaign_redeems"
  ADD CONSTRAINT "fk_campaign_redeems_campaign_id"
  FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "campaign_redeems"
  ADD CONSTRAINT "fk_campaign_redeems_card_id"
  FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "purchase_types"
  ADD CONSTRAINT "fk_purchase_types_card_type_id"
  FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "purchases"
  ADD CONSTRAINT "fk_purchases_purchase_type_id"
  FOREIGN KEY ("purchase_type_id") REFERENCES "purchase_types" ("id");

ALTER TABLE "purchases"
  ADD CONSTRAINT "fk_purchases_card_id"
  FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "store_theme"
  ADD CONSTRAINT "fk_store_theme_store_id"
  FOREIGN KEY ("store_id") REFERENCES "stores" ("id");

ALTER TABLE "franchise_theme"
  ADD CONSTRAINT "fk_franchise_theme_franchise_id"
  FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "push_notifications"
  ADD CONSTRAINT "fk_push_notifications_card_type_id"
  FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "push_notification_cards"
  ADD CONSTRAINT "fk_push_notification_cards_push_notification_id"
  FOREIGN KEY ("push_notification_id") REFERENCES "push_notifications" ("id");

ALTER TABLE "push_notification_cards"
  ADD CONSTRAINT "fk_push_notification_cards_card_id"
  FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "campaign_stores"
  ADD CONSTRAINT "fk_campaign_stores_campaign_id"
  FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "campaign_stores"
  ADD CONSTRAINT "fk_campaign_stores_store_id"
  FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
