CREATE TABLE "stores" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "store_admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "store_id" integer,
  "name" text,
  "username" text UNIQUE,
  "password" text,
  "role" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "campaigns" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" integer,
  "points" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" text,
  "username" text,
  "password" text,
  "token" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "campaign_redeems" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "campaign_id" integer,
  "card_id" integer,
  "amount" integer,
  "points" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "card_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "store_id" integer,
  "name" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "user_id" integer,
  "card_type_id" integer,
  "points" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "purchases" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "purchase_type_id" integer,
  "card_id" integer,
  "points" integer,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "purchase_types" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" integer,
  "points" integer,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "store_theme" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "store_id" integer,
  "primary_color" text,
  "secondary_color" text,
  "background_color" text,
  "text_color" text,
  "stamp_image_url" text,
  "slot_image_url" text,
  "card_background_image_url" text,
  "logo_url" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "push_notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "card_type_id" integer,
  "status" integer,
  "description" text,
  "message" text,
  "push_date" timestamp,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "push_notification_cards" (
  "push_notification_id" integer,
  "card_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  PRIMARY KEY ("push_notification_id", "card_id")
);

CREATE TABLE "fidely_admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
  "name" text,
  "username" text,
  "password" text,
  "role" integer
);

ALTER TABLE "store_admin" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id");

ALTER TABLE "campaigns" ADD FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "campaign_redeems" ADD FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "campaign_redeems" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "card_types" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "cards" ADD FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "purchases" ADD FOREIGN KEY ("purchase_type_id") REFERENCES "purchase_types" ("id");

ALTER TABLE "purchases" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");

ALTER TABLE "purchase_types" ADD FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "store_theme" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id");

ALTER TABLE "push_notifications" ADD FOREIGN KEY ("card_type_id") REFERENCES "card_types" ("id");

ALTER TABLE "push_notification_cards" ADD FOREIGN KEY ("push_notification_id") REFERENCES "push_notifications" ("id");

ALTER TABLE "push_notification_cards" ADD FOREIGN KEY ("card_id") REFERENCES "cards" ("id");
