CREATE TABLE "push_notifications" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "card_type_id" INTEGER NOT NULL,
    "status" INTEGER NOT NULL,
    "description" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "push_date" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);
