CREATE TABLE "franchises" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "name" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

ALTER TABLE "stores"
    ADD COLUMN "franchise_id" INTEGER;

ALTER TABLE "store_admin"
    ADD COLUMN "franchise_id" INTEGER;

ALTER TABLE "card_types"
    DROP CONSTRAINT IF EXISTS "fk_card_types_store_id";

ALTER TABLE "card_types"
    DROP COLUMN IF EXISTS "store_id";

ALTER TABLE "card_types"
    ADD COLUMN "franchise_id" INTEGER;

CREATE TABLE "franchise_theme" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "franchise_id" INTEGER NOT NULL UNIQUE,
    "primary_color" TEXT NOT NULL,
    "secondary_color" TEXT NOT NULL,
    "background_color" TEXT NOT NULL,
    "text_color" TEXT NOT NULL,
    "stamp_image_url" TEXT NOT NULL,
    "slot_image_url" TEXT NOT NULL,
    "card_background_image_url" TEXT NOT NULL,
    "logo_url" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE "campaign_stores" (
    "campaign_id" INTEGER NOT NULL,
    "store_id" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    PRIMARY KEY ("campaign_id", "store_id")
);

ALTER TABLE "stores"
    ADD CONSTRAINT "fk_stores_franchise_id"
    FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "store_admin"
    ADD CONSTRAINT "fk_store_admin_franchise_id"
    FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "card_types"
    ADD CONSTRAINT "fk_card_types_franchise_id"
    FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "franchise_theme"
    ADD CONSTRAINT "fk_franchise_theme_franchise_id"
    FOREIGN KEY ("franchise_id") REFERENCES "franchises" ("id");

ALTER TABLE "campaign_stores"
    ADD CONSTRAINT "fk_campaign_stores_campaign_id"
    FOREIGN KEY ("campaign_id") REFERENCES "campaigns" ("id");

ALTER TABLE "campaign_stores"
    ADD CONSTRAINT "fk_campaign_stores_store_id"
    FOREIGN KEY ("store_id") REFERENCES "stores" ("id");
