ALTER TABLE "store_admin"
    RENAME COLUMN "password" TO "password_hash";

ALTER TABLE "fidely_admin"
    RENAME COLUMN "password" TO "password_hash";

CREATE UNIQUE INDEX "uq_fidely_admin_username"
    ON "fidely_admin" ("username");

CREATE TABLE "admin_sessions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    "admin_type" TEXT NOT NULL,
    "admin_id" INTEGER NOT NULL,
    "session_token_hash" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL,
    "last_seen_at" TIMESTAMPTZ,
    CONSTRAINT "chk_admin_sessions_admin_type"
        CHECK ("admin_type" IN ('store_admin', 'fidely_admin'))
);

CREATE UNIQUE INDEX "uq_admin_sessions_session_token_hash"
    ON "admin_sessions" ("session_token_hash");

CREATE INDEX "idx_admin_sessions_admin_lookup"
    ON "admin_sessions" ("admin_type", "admin_id");

CREATE INDEX "idx_admin_sessions_expires_at"
    ON "admin_sessions" ("expires_at");
